config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :students
  resources :exams
  resources :teachers
  resources :reports

  # get 'reports/index'
  # get 'reports/show'
  # get 'reports/new'
  # get 'reports/edit'
  # get 'reports/update'
  # get 'reports/destroy'
  # get 'teachers/index'
  # get 'teachers/show'
  # get 'teachers/new'
  # get 'teachers/edit'
  # get 'teachers/update'
  # get 'teachers/destroy'
  # get 'exams/index'
  # get 'exams/show'
  # get 'exams/new'
  # get 'exams/edit'
  # get 'exams/update'
  # get 'exams/destroy'
  # get 'students/index'
  # get 'students/show'
  # get 'students/new'
  # get 'students/edit'
  # get 'students/update'
  # get 'students/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
    @exams = Exam.all
  end

  def show
    id = params[:id]
    @exam = Exam.find(id)
  end

  def new
    @exam = Exam.new
  end

  def create
    exam = Exam.new(parameter)
    exam.save
    redirect_to exams_path
  end

  def edit
    @exam = Exam.find(params[:id])
  end

  def update
    @exam = Exam.find(params[:id])
    @exam.update(parameter)
    # puts book.errors.messages
    # flash[:notice] = 'A Book has been updated'
    redirect_to exam_path(@exam)
  end

  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy()
    # flash[:notice] = 'A Book has been deleted'
    redirect_to exams_path
  end

  private
  def parameter
    params.require(:exam).permit(:title, :duration, :nilai, :aktif, :level, :student_id, :mapel,) #ambil parameter dari inputan require
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @repts = Report.all
  end

  def show
    id = params[:id]
    @rept = Report.find(id)
  end

  def new
    @rept = Report.new
  end

  def create
    rept = Report.new(parameter)
    rept.save
    redirect_to reports_path
  end

  def edit
    @rept = Report.find(params[:id])
  end

  def update
    @rept = Report.find(params[:id])
    @rept.update(parameter)
    # puts book.errors.messages
    # flash[:notice] = 'A Book has been updated'
    redirect_to report_path(@rept)
  end

  def destroy
    @rept = Report.find(params[:id])
    @rept.destroy()
    # flash[:notice] = 'A Book has been deleted'
    redirect_to reports_path
  end

  private
  def parameter
    params.require(:report).permit(:title, :hasil, :teacher_id, :student_id, :mapel, :date) #ambil parameter dari inputan require
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    id = params[:id]
    @stud = Student.find(id)
  end

  def new
    @stud = Student.new
  end

  def create
    stud = Student.new(parameter)
    stud.save
    redirect_to students_path
  end

  def edit
    @stud = Student.find(params[:id])
  end

  def update
    @stud = Student.find(params[:id])
    @stud.update(parameter)
    # puts book.errors.messages
    # flash[:notice] = 'A Book has been updated'
    redirect_to student_path(@stud)
  end

  def destroy
    @stud = Student.find(params[:id])
    @stud.destroy()
    # flash[:notice] = 'A Book has been deleted'
    redirect_to students_path
  end

  private
  def parameter
    params.require(:student).permit(:nik, :name, :username, :age, :kelas, :adress, :city) #ambil parameter dari inputan require
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachs = Teacher.all
  end

  def show
    id = params[:id]
    @teac = Teacher.find(id)
  end

  def new
    @teac = Teacher.new
  end

  def create
    teac = Teacher.new(parameter)
    teac.save
    redirect_to teachers_path
  end

  def edit
    @teac = Teacher.find(params[:id])
  end

  def update
    @teac = Teacher.find(params[:id])
    @teac.update(parameter)
    # puts book.errors.messages
    # flash[:notice] = 'A Book has been updated'
    redirect_to teacher_path(@teac)
  end

  def destroy
    @teac = Teacher.find(params[:id])
    @teac.destroy()
    # flash[:notice] = 'A Book has been deleted'
    redirect_to teachers_path
  end

  private
  def parameter
    params.require(:teacher).permit(:nik, :name, :age, :kelas, :mapel) #ambil parameter dari inputan require
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/exams/destroy.html.erb
<h1>Exams#destroy</h1>
<p>Find me in app/views/exams/destroy.html.erb</p>

app/views/exams/edit.html.erb
<h1>Exams#edit</h1>
<p>Find me in app/views/exams/edit.html.erb</p>

<%= form_for(@exam) do |f| %>
    <div class="form-group row justify-content-between">
        <%= f.label :title, :class => "col-sm-2 "   %>
        <%= f.text_field :title, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :nilai, :class => "col-sm-2 "   %>
        <%= f.text_field :nilai, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :mapel, :class => "col-sm-2 "   %>
        <%= f.text_field :mapel, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :student_id, :class => "col-sm-2 "   %>
        <%= f.text_field :student_id, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :duration, :class => "col-sm-2 "   %>
        <%= f.text_field :duration, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :aktif, :class => "col-sm-2 "   %>
        <%= f.text_field :aktif, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :level, :class => "col-sm-2 "   %>
        <%= f.text_field :level, :class => " form-control"  %>
    </div>
    <div class="row ">
        <div class="col-sm-7 ">
            <%= f.submit "Save", :class=> "btn btn-primary" %>
        </div>
    </div>
<%end%>

app/views/exams/index.html.erb
<h1>Exams#index</h1>
<p>Find me in app/views/exams/index.html.erb</p>

<table>
<tr>
    <td>Judul</td>
    <td>Mapel</td>
    <td>Durasi</td>
    <td>Nilai</td>
    <td>Aktif</td>
    <td>Level</td>
    <td>ID Siswa</td>

</tr>
<% @exams.each do |s|%>
<tr>
    <td><%= s.title%></td>
    <td><%= s.mapel%></td>
    <td><%= s.duration%></td>
    <td><%= s.nilai%></td>
    <td><%= s.aktif%></td>
    <td><%= s.level%></td>
    <td><%= s.student_id%></td>
    <td>

    <%= link_to 'Detail', exam_path(s)%> | 
    <%= link_to 'Edit', edit_exam_path(s)%> | 
    <%= link_to 'Delete', exam_path(s), method: :delete, data: {confirm: 'Are you sure'}%> | 
    </td>
</tr>
<%end%>
</table>

<%= link_to 'New Exam', new_exam_path%>

app/views/exams/new.html.erb
<h1>Exams#new</h1>
<p>Find me in app/views/exams/new.html.erb</p>

<%= form_for(@exam) do |f| %>
    <div class="form-group row justify-content-between">
        <%= f.label :title, :class => "col-sm-2 "   %>
        <%= f.text_field :title, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :nilai, :class => "col-sm-2 "   %>
        <%= f.text_field :nilai, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :mapel, :class => "col-sm-2 "   %>
        <%= f.text_field :mapel, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :student_id, :class => "col-sm-2 "   %>
        <%= f.text_field :student_id, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :duration, :class => "col-sm-2 "   %>
        <%= f.text_field :duration, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :aktif, :class => "col-sm-2 "   %>
        <%= f.text_field :aktif, :class => " form-control"  %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :level, :class => "col-sm-2 "   %>
        <%= f.text_field :level, :class => " form-control"  %>
    </div>
    <div class="row ">
        <div class="col-sm-7 ">
            <%= f.submit "Save", :class=> "btn btn-primary" %>
        </div>
    </div>
<%end%>

app/views/exams/show.html.erb
<h1>Exams#show</h1>
<p>Find me in app/views/exams/show.html.erb</p>

Judul : <%= @exam.title%> </br>
Hasil : <%= @exam.nilai%> </br>
Mapel : <%= @exam.mapel%> </br>
ID Siswa : <%= @exam.student_id%> </br>
Status : <% if @exam.aktif == false 
'Tidak lulus' 
else 
'Lulus'
end%> </br>
Level : <%= @exam.level%> </br>
Duration : <%= @exam.duration%> </br>
Nilai : <%= @exam.nilai%> </br>

app/views/exams/update.html.erb
<h1>Exams#update</h1>
<p>Find me in app/views/exams/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KejarId</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/destroy.html.erb
<h1>Reports#destroy</h1>
<p>Find me in app/views/reports/destroy.html.erb</p>

app/views/reports/edit.html.erb
<h1>Reports#edit</h1>
<p>Find me in app/views/reports/edit.html.erb</p>

<%= form_for(@rept) do |f| %>
    <div class="form-group row justify-content-between">
        <%= f.label :title, :class => "col-sm-2 "   %>
        <%= f.text_field :title, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :hasil, :class => "col-sm-2 "   %>
        <%= f.text_field :hasil, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :mapel, :class => "col-sm-2 "   %>
        <%= f.text_field :mapel, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :student_id, :class => "col-sm-2 "   %>
        <%= f.text_field :student_id, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :teacher_id, :class => "col-sm-2 "   %>
        <%= f.text_field :teacher_id, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :date, :class => "col-sm-2 "   %>
        <%= f.text_field :date, :class => " form-control" %>
    </div>

    <div class="row ">
        <div class="col-sm-7 ">
            <%= f.submit "Save", :class=> "btn btn-primary" %>
        </div>
    </div>
<%end%>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>
<table class="table">
<tr>
    <td>Title</td>
    <td>Hasil</td>
    <td>Mapel</td>
    <td>ID Murid</td>
    <td>ID Guru</td>
    <td>Date</td>
</tr>
<% @repts.each do |s|%>
<tr>
    <td><%= s.title%></td>
    <td><%= s.hasil%></td>
    <td><%= s.mapel%></td>
    <td><%= s.student_id%></td>
    <td><%= s.teacher_id%></td>
    <td><%= s.date%></td>
    <td>
    <%= link_to 'Detail', report_path(s)%> | 
    <%= link_to 'Edit', edit_report_path(s)%> | 
    <%= link_to 'Delete', report_path(s), method: :delete, data: {confirm: 'Are you sure'}%> | 
    </td>
</tr>
<%end%>
</table>

<%= link_to 'New Report', new_report_path%>

app/views/reports/new.html.erb
<h1>Reports#new</h1>
<p>Find me in app/views/reports/new.html.erb</p>

<%= form_for(@rept) do |f| %>
    <div class="form-group row justify-content-between">
        <%= f.label :title, :class => "col-sm-2 "   %>
        <%= f.text_field :title, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :hasil, :class => "col-sm-2 "   %>
        <%= f.text_field :hasil, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :mapel, :class => "col-sm-2 "   %>
        <%= f.text_field :mapel, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :student_id, :class => "col-sm-2 "   %>
        <%= f.text_field :student_id, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :teacher_id, :class => "col-sm-2 "   %>
        <%= f.text_field :teacher_id, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :date, :class => "col-sm-2 "   %>
        <%= f.text_field :date, :class => " form-control" %>
    </div>

    <div class="row ">
        <div class="col-sm-7 ">
            <%= f.submit "Save", :class=> "btn btn-primary" %>
        </div>
    </div>
<%end%>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>

Judul : <%= @rept.title%> </br>
Hasil : <%= @rept.hasil%> </br>
Mapel : <%= @rept.mapel%> </br>
ID Siswa : <%= @rept.student_id%> </br>
ID Guru: <%= @rept.teacher_id%> </br>
Tanggal : <%= @rept.date%> </br>

app/views/reports/update.html.erb
<h1>Reports#update</h1>
<p>Find me in app/views/reports/update.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

<%= form_for(@stud) do |f| %>
    <div class="form-group row justify-content-between">
        <%= f.label :nik, :class => "col-sm-1 "  %>
        <%= f.text_field :nik, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :name, :class => "col-sm-1 " %>
        <%= f.text_field :name, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :username, :class => "col-sm-1 " %>
        <%= f.text_field :username, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :age, :class => "col-sm-1 " %>
        <%= f.text_field :age, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :kelas, :class => "col-sm-1 " %>
        <%= f.text_field :kelas, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :city, :class => "col-sm-1 " %>
        <%= f.text_field :city, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :adress, :class => "col-sm-1 " %>
        <%= f.text_area :adress, :class => " form-control" %>
    </div>
    <div class="row ">
        <div class="col-sm-7 ">
            <%= f.submit "Save", :class=> "btn btn-primary" %>
        </div>
    </div>
<%end%>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>
<table class="table">
<tr>
    <td>NIK</td>
    <td>Nama</td>
    <td>Username</td>
    <td>Umur</td>
    <td>Kelas</td>
    <td>Kota</td>
    <td>Alamat</td>

</tr>
<% @students.each do |s|%>
<tr>
    <td><%= s.nik%></td>
    <td><%= s.name%></td>
    <td><%= s.username%></td>
    <td><%= s.age%></td>
    <td><%= s.kelas%></td>
    <td><%= s.city%></td>
    <td><%= s.adress%></td>

    <td>
    <%= link_to 'Detail', student_path(s)%> | 
    <%= link_to 'Edit', edit_student_path(s)%> | 
    <%= link_to 'Delete', student_path(s), method: :delete, data: {confirm: 'Are you sure'}%> | 
    </td>
</tr>
<%end%>
</table>

<%= link_to 'New Student', new_student_path%>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

<%= form_for(@stud) do |f| %>
    <div class="form-group row justify-content-between">
        <%= f.label :nik, :class => "col-sm-1 "  %>
        <%= f.text_field :nik, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :name, :class => "col-sm-1 " %>
        <%= f.text_field :name, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :username, :class => "col-sm-1 " %>
        <%= f.text_field :username, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :age, :class => "col-sm-1 " %>
        <%= f.text_field :age, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :kelas, :class => "col-sm-1 " %>
        <%= f.text_field :kelas, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :city, :class => "col-sm-1 " %>
        <%= f.text_field :city, :class => " form-control" %>
    </div>

    <div class="form-group row justify-content-between">
        <%= f.label :adress, :class => "col-sm-1 " %>
        <%= f.text_area :adress, :class => " form-control" %>
    </div>
    <div class="row ">
        <div class="col-sm-7 ">
            <%= f.submit "Save", :class=> "btn btn-primary" %>
        </div>
    </div>
<%end%>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

NIK : <%= @stud.nik%> </br>
Name : <%= @stud.name%> </br>
Age : <%= @stud.age%> </br>
Username : <%= @stud.username%> </br>
Class : <%= @stud.kelas%> </br>
City : <%= @stud.city%> </br>
Address : <%= @stud.adress%> </br>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>

app/views/teachers/destroy.html.erb
<h1>Teachers#destroy</h1>
<p>Find me in app/views/teachers/destroy.html.erb</p>

app/views/teachers/edit.html.erb
<h1>Teachers#edit</h1>
<p>Find me in app/views/teachers/edit.html.erb</p>

<%= form_for(@teac) do |f| %>
    <div class="form-group row justify-content-between">
        <%= f.label :nik, :class => "col-sm-2 " %>
        <%= f.text_field :nik, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :name, :class => "col-sm-2 " %>
        <%= f.text_field :name, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :age, :class => "col-sm-2 " %>
        <%= f.text_field :age, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :kelas, :class => "col-sm-2 " %>
        <%= f.text_field :kelas, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :mapel, :class => "col-sm-2 " %>
        <%= f.text_field :mapel, :class => " form-control" %>
    </div>
    <div class="row ">
        <div class="col-sm-7 ">
            <%= f.submit "Save", :class=> "btn btn-primary" %>
        </div>
    </div>
<%end%>

app/views/teachers/index.html.erb
<h1>Teachers#index</h1>
<p>Find me in app/views/teachers/index.html.erb</p>
<table class="table">
<tr>
    <td>NIK</td>
    <td>Nama</td>
    <td>Umur</td>
    <td>Kelas</td>
    <td>Mapel</td>

</tr>
<% @teachs.each do |t|%>
<tr>
    <td><%= t.nik%></td>
    <td><%= t.name%></td>
    <td><%= t.age%></td>
    <td><%= t.kelas%></td>
    <td><%= t.mapel%></td>

    <td>
    <%= link_to 'Detail', teacher_path(t)%> | 
    <%= link_to 'Edit', edit_teacher_path(t)%> | 
    <%= link_to 'Delete', teacher_path(t), method: :delete, data: {confirm: 'Are you sure'}%> | 
    </td>
</tr>
<%end%>
</table>

<%= link_to 'New Teacher', new_teacher_path%>

app/views/teachers/new.html.erb
<h1>Teachers#new</h1>
<p>Find me in app/views/teachers/new.html.erb</p>

<%= form_for(@teac) do |f| %>
    <div class="form-group row justify-content-between">
        <%= f.label :nik, :class => "col-sm-2 " %>
        <%= f.text_field :nik, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :name, :class => "col-sm-2 " %>
        <%= f.text_field :name, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :age, :class => "col-sm-2 " %>
        <%= f.text_field :age, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :kelas, :class => "col-sm-2 " %>
        <%= f.text_field :kelas, :class => " form-control" %>
    </div>
    <div class="form-group row justify-content-between">
        <%= f.label :mapel, :class => "col-sm-2 " %>
        <%= f.text_field :mapel, :class => " form-control" %>
    </div>
    <div class="row ">
        <div class="col-sm-7 ">
            <%= f.submit "Save", :class=> "btn btn-primary" %>
        </div>
    </div>
<%end%>

app/views/teachers/show.html.erb
<h1>Teachers#show</h1>
<p>Find me in app/views/teachers/show.html.erb</p>

NIK : <%= @teac.nik%> </br>
Nama : <%= @teac.name%> </br>
Umur : <%= @teac.age%> </br>
Kelas : <%= @teac.kelas%> </br>
Mapel : <%= @teac.mapel%> </br>

app/views/teachers/update.html.erb
<h1>Teachers#update</h1>
<p>Find me in app/views/teachers/update.html.erb</p>

app/views/welcome/index.html.erb
<h2>Hi, Welcome to my project website!</h2>
<p>Down below are the main links in this website.</p>
<ul>
    <li><%= link_to 'Students', students_path()%> </li>
    <li><%= link_to 'Teachers', teachers_path()%> </li>
    <li><%= link_to 'Exams', exams_path()%> </li>
    <li><%= link_to 'Reports', reports_path()%> </li>

</ul>
<p>
  The time is now: <%= Time.now %>
</p>